scalar Date

type DepartmentEmployeeDTO {
    departmentId: String
    fromDate: String
    toDate: String
}

type SalaryEmployeeDTO {
    amount: Long
    fromDate: String
    toDate: String
}

type TitleEmployeeDTO {
    title: String
    fromDate: String
    toDate: String
}

type EmployeeDTO {
    id: Long
    birthDate: String
    firstName: String
    lastName: String
    gender: String
    hireDate: String
    active: Boolean
    departments: [DepartmentEmployeeDTO]
    salaries: [SalaryEmployeeDTO]
    titles: [TitleEmployeeDTO]
}

input DepartmentEmployeeInputDTO {
    departmentId: String
    fromDate: Date
    toDate: Date
}

input SalaryEmployeeInputDTO {
    amount: Long
    fromDate: Date
    toDate: Date
}

input TitleEmployeeInputDTO {
    title: String
    fromDate: Date
    toDate: Date
}

input EmployeeInputDTO {
    birthDate: Date
    firstName: String
    lastName: String
    gender: String
    hireDate: Date
    active: Boolean
    createdBy: Long
    updatedBy: Long
    departments: [DepartmentEmployeeInputDTO]
    salaries: [SalaryEmployeeInputDTO]
    titles: [TitleEmployeeInputDTO]
}

extend type Query {
    getAllEmployees: [EmployeeDTO]
    getEmployeeById(id: ID!): EmployeeDTO
}

extend type Mutation {
  saveEmployee(input: EmployeeInputDTO!): EmployeeDTO
  updateEmployee(id: ID!, input: EmployeeInputDTO!): EmployeeDTO
  deleteEmployee(id: ID!): Boolean
}